var images_rotate = [
    {"image": "quiver300.png", "caption": "quiver(X, Y, U, V)", "link": "plot_types/arrays/quiver.html"},
    {"image": "imshow300.png", "caption": "imshow(Z)", "link": "plot_types/arrays/imshow.html"},
    {"image": "pcolormesh300.png", "caption": "pcolormesh(X, Y, Z)", "link": "plot_types/arrays/pcolormesh.html"},
    {"image": "contourf300.png", "caption": "contourf(X, Y, Z)", "link": "plot_types/arrays/contourf.html"},
    {"image": "barbs300.png", "caption": "barbs(X, Y U, V)", "link": "plot_types/arrays/barbs.html"},
    {"image": "contour300.png", "caption": "contour(X, Y, Z)", "link": "plot_types/arrays/contour.html"},
    {"image": "streamplot300.png", "caption": "streamplot(X, Y, U, V)", "link": "plot_types/arrays/streamplot.html"},
    {"image": "plot300.png", "caption": "plot(x, y)", "link": "plot_types/basic/plot.html"},
    {"image": "fill_between300.png", "caption": "fill_between(x, y1, y2)", "link": "plot_types/basic/fill_between.html"},
    {"image": "step300.png", "caption": "step(x, y)", "link": "plot_types/basic/step.html"},
    {"image": "scatter_plot300.png", "caption": "scatter(x, y)", "link": "plot_types/basic/scatter_plot.html"},
    {"image": "stem300.png", "caption": "stem(x, y)", "link": "plot_types/basic/stem.html"},
    {"image": "bar300.png", "caption": "bar(x, height) / barh(y, width)", "link": "plot_types/basic/bar.html"},
    {"image": "hist_plot300.png", "caption": "hist(x)", "link": "plot_types/stats/hist_plot.html"},
    {"image": "hist2d300.png", "caption": "hist2d(x, y)", "link": "plot_types/stats/hist2d.html"},
    {"image": "pie300.png", "caption": "pie(x)", "link": "plot_types/stats/pie.html"},
    {"image": "hexbin300.png", "caption": "hexbin(x, y, C)", "link": "plot_types/stats/hexbin.html"},
    {"image": "boxplot_plot300.png", "caption": "boxplot(X)", "link": "plot_types/stats/boxplot_plot.html"},
    {"image": "violin300.png", "caption": "violinplot(D)", "link": "plot_types/stats/violin.html"},
    {"image": "errorbar_plot300.png", "caption": "errorbar(x, y, yerr, xerr)", "link": "plot_types/stats/errorbar_plot.html"},
    {"image": "eventplot300.png", "caption": "eventplot(D)", "link": "plot_types/stats/eventplot.html"},
];